export const Users = [
    {
        "id": 1,
        "first_name": "Emilie",
        "last_name": "Clark",
        "email": "mfiudhvi@jfu.com",
        "gender": "female",
    },
    {
        "id": 2,
        "first_name": "Jason",
        "last_name": "Roy",
        "email": "lknviofh@rfi.com",
        "gender": "Male",
    },
    {
        "id": 3,
        "first_name": "Rohit",
        "last_name": "Jain",
        "email": "lniufi@nvi.com",
        "gender": "Male",
    },
    {
        "id": 4,
        "first_name": "Alex",
        "last_name": "Ray",
        "email": "ldnvos@nci.com",
        "gender": "Male",
    },
    {
        "id": 5,
        "first_name": "Daisy",
        "last_name": "Jones",
        "email": "lnvoids@mid.com",
        "gender": "Female",
    },
    {
        "id": 6,
        "first_name": "Rajat",
        "last_name": "Thakur",
        "email": "lkfoish@nf.com",
        "gender": "Male",
    },
    {
        "id": 7,
        "first_name": "Lily",
        "last_name": "Lara",
        "email": "hvsufgb@nbdcu.com",
        "gender": "Female",
    },
    {
        "id": 8,
        "first_name": "Ankit",
        "last_name": "Rana",
        "email": "gegfib@njisg.com",
        "gender": "Male",
    },
    {
        "id": 9,
        "first_name": "Rupa",
        "last_name": "Jain",
        "email": "fgbbssooh@njhds.com",
        "gender": "Female",
    },
    {
        "id": 10,
        "first_name": "Shlok",
        "last_name": "Pandit",
        "email": "lksfois@lkbd.com",
        "gender": "Male",
    },
]